name: Auto Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Łączenie z EC2 i aktualizacja kodu
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 20m
          envs: CONNECTION_STRING,COGNITO_AUTHORITY,COGNITO_AUDIENCE,COGNITO_REGION,VITE_API_URL
          script: |
            cd /home/ubuntu/Twittex

            git fetch origin main
            git reset --hard origin/main

            cat > .env <<EOF
            ConnectionStrings__DefaultConnection=$CONNECTION_STRING
            Cognito__Authority=$COGNITO_AUTHORITY
            Cognito__Audience=$COGNITO_AUDIENCE
            Cognito__Region=$COGNITO_REGION
            VITE_API_URL=$VITE_API_URL
            EOF

            sudo docker kill $(sudo docker ps -q) 2>/dev/null || true
            sudo docker rm $(sudo docker ps -aq) 2>/dev/null || true
            sudo docker compose up -d --build
            sudo docker image prune -f
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          COGNITO_AUTHORITY: ${{ secrets.COGNITO_AUTHORITY }}
          COGNITO_AUDIENCE: ${{ secrets.COGNITO_AUDIENCE }}
          COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}